### ISSUE TITLE
IMM Review

### ISSUE THREAD

**Issue by idg10** [corvus-dotnet/Corvus.Configuration#50]
Go through every item on the IP Maturity Matrix and ensure it is up to date, adding work items in any areas that could be improved

- [x] **Shared Engineering Standards**
- [x] **Coding Standards**
- [x] **Executable Specifications** #73
- [x] **Code Coverage**
- [x] **Benchmarks** #74
- [x] **Reference Documentation**
- [x] **Design & Implementation Documentation** #75
- [x] **How-to Documentation** #82 
- [x] **Date of Last IP Review**
- [x] **Framework Version**
- [x] **Associated Work Items** #76
- [x] **Source Code Availability**
- [x] **License**: Apache 2.0
- [x] **Production Use**
- [x] **Insights**
- [x] **Packaging** #77
- [x] **Deployment**
- [x] **Next IMM review** #78
